apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-first-app-deployment
  labels:
    app: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      hai: hello
  template:
    metadata:
      labels:
        hai: hello
    spec:
      containers:
      - name: my-first-app-container
        image: nginx:latest # This will pull the latest Nginx image
        ports:
        - containerPort: 80
